# app_test.yml

# 本地
mysql:
  host: 127.0.0.1
  username: root
  password: password
  port: 3306
  db: hainiu
  charset: utf8mb4

#mysql:
#  host: 127.0.0.1
#  username: u_hainiu
#  password: hainiu@2022
#  port: 3306
#  db: db_haibao
#  charset: utf8

# 选择用Redis单机还是集群 填入redis或redisCLuster
cache: redisCluster

redisCluster:
  0: "127.0.0.1:7000"
  1: "127.0.0.1:7001"
  2: "127.0.0.1:7002"
  3: "127.0.0.1:7003"
  4: "127.0.0.1:7004"
  5: "127.0.0.1:7005"

redis:
  host: 127.0.0.1
  password: ''
  port: 6379
  timeout: 3600
  select: 0

server:
  name: "ws server"
  scheme: "ws"
  ip: "127.0.0.1"
  Port: 6031
  heartBeatTime: 60
  inChanSize: 1024
  outChanSize: 1024
  workerPoolSize: 4
  maxWorkTaskLen: 10
  maxConn: 1000